### PR TITLE
FIX for #35: Webpack 5 compatibility

### PR DESCRIPTION
**Pull request by Dan503**
Since the entry file is .mjs Webpack 5 requires me to specify `.js` on all the imports.

### CODE REVIEW

**Comment by Dan503** [comment]
Fixes issue #35 

Waiting for author of issue to see if the beta release fixes the issue.

**Comment by jameschristopher** [comment]
Is there any movement on getting this PR merged into a release? I'd be happy to contribute, coding, testing, or otherwise. :)

**Comment by Dan503** [comment]
@jameschristopher I've merged and published now. v1.0.11 should be Webpack 5 compatible

**Comment by jameschristopher** [comment]
Thank you!!

**Pull request merged**
