### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by sandaruSL**

### CODE REVIEW

**Comment by Dan503** [comment]
I'm not that familiar with the .gitattributes file. Mind explaining what this commit does?

**Comment by sandaruSL** [comment]
I just want creat pull request to our event. Thats the reason i creat edit with" . " sory for that

**Comment by sandaruSL** [comment]
But "." Can change many things

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Dan503** [comment]
Can you link me to an article explaining the benefit?

**Pull request closed without merging**
